use lazy_static::lazy_static;

// These strings are required for the crate to run!
lazy_static! {
    pub static ref STRINGS: Vec<&'static str> = vec![
        "AcquireSRWLockExclusive",
        "ADVAPI32.dll",
        "CloseHandle",
        "CreateFileA",
        "CreateProcessA",
        "CreateRemoteThread",
        "CreateToolhelp32Snapshot",
        "CryptAcquireContextW",
        "CryptCreateHash",
        "CryptDecrypt",
        "CryptDeriveKey",
        "CryptDestroyHash",
        "CryptDestroyKey",
        "CryptGetKeyParam",
        "CryptHashData",
        "CryptReleaseContext",
        "CryptSetKeyParam",
        "GetCurrentProcess",
        "GetLastError",
        "GetProcAddress",
        "GetSystemDirectoryA",
        "GetSystemDirectoryW",
        "KERNEL32.DLL",
        "LoadLibraryA",
        "MessageBoxA",
        "NTDLL.dll",
        "NtFlushInstructionCache",
        "OpenFile",
        "OpenProcess",
        "Process32First",
        "Process32Next",
        "ReflectiveLoader",
        "ResumeThread",
        "RtlMoveMemory",
        "USER32.dll",
        "VirtualAlloc",
        "VirtualAllocEx",
        "VirtualFree",
        "VirtualFreeEx",
        "VirtualProtect",
        "WaitForSingleObject",
        "WriteFile",
        "WriteProcessMemory",
    ];
}
